concentration_game/config/routes.rb
Rails.application.routes.draw do

  resources :games, only: [:create, :show]
  post "games/turn"
  resources :players, only: [:create]
  root "games#welcome"

end

concentration_game/app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  validates_presence_of :value, :suit, :face, :deck_id, allow_blank: false

  p = ["11", "12", "13", "14", "15", "21", "22", "23", "24", "25", "31", "32", "33", "34", "35"]

  CSS_VALUE_MATCHING = {
    2 => [p[5], p[9]], 3 => [p[5], p[9], p[7]], 4 => [p[0], p[4], p[10], p[14]], 5 => [p[0], p[4], p[10], p[14], p[7]],
    6 => [p[0], p[2], p[4], p[10], p[12], p[14]], 7 => [p[0], p[2], p[4], p[10], p[12], p[14], p[6]], 8 => [p[0], p[2], p[4], p[10], p[12], p[14], p[6], p[8]],
    9 => [p[0], p[1], p[3], p[4], p[14], p[13], p[11], p[10], p[7]], 10 => [p[0], p[1], p[3], p[4], p[14], p[13], p[11], p[10], p[8], p[6]]
}

  def is_matching?(another_card)
    value == another_card.value ? true : false
  end
end

concentration_game/app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :game
  has_many :cards

  def shuffle
    cards.where(matched: false).shuffle
  end

  def set_cards_as_unmatched
    cards.all.each do |card|
      card.matched = false
      card.save
    end
  end

end

concentration_game/app/models/game.rb
class Game < ActiveRecord::Base

  has_one :deck
  has_one :player
  has_many :cards, through: :deck

  def reset
    update_attributes(turn: 0)
    player.update_attributes(points: 0)
    deck.set_cards_as_unmatched
  end

end

concentration_game/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game

  validates_presence_of :name, :game_id, allow_blank: false
end

concentration_game/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

concentration_game/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :get_game_and_player, only: [:show, :turn]
  before_action :start_new_game, only: [:show]
  before_action :set_variables_for_each_turn, only: [:turn]

  def welcome

  end

  def create
    @game = Game.new(games_params)
    if @game.save
      @game.deck = Deck.first
    end
  end

  def show

  end

  def turn
    @game.update_attributes(turn: @game.turn += 1)

    if @card_one.is_matching?(@card_two)
      @card_one.update_attributes(matched: true) && @card_two.update_attributes(matched: true)
      @player.update_attributes(points: @player.points += 1)
      @new_cards = @cards_left.shift(2)
    else
      @player.update_attributes(points: @player.points -= 1)
    end

    respond_to do |format|
      format.js
    end
  end

private

  def get_game_and_player
    @game = Game.find_by(id: params[:id])
    @player = @game.player
  end

  def start_new_game
    @game.reset
    @cards_left = @game.deck.shuffle
    @cards_on_board = @cards_left.shift(22)
  end

  def set_variables_for_each_turn
    @cards_left = Card.where(id: params[:cards_left].split(" ")).shuffle
    @card_one = Card.find_by(id: params[:card_one_id])
    @card_two = Card.find_by(id: params[:card_two_id])
  end

  def games_params
    params.require(:game).permit(:name, :turn)
  end

end

concentration_game/app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to game_path(@player.game)
    else
      flash.now[:alert] = "#{@player.errors.full_messages.to_sentence}"
    end
  end

private

  def player_params
    params.require(:player).permit(:name, :game_id, :points)
  end

end

concentration_game/app/helpers/application_helper.rb
module ApplicationHelper

  def present(object, klass=nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end

end

concentration_game/app/views/cards/_blank_card.html.erb
<div class="col-xs-2">
  <div class="card-wrapper">
    <div class="card">
        <div class="front"></div>
    </div>
  </div>
</div>

concentration_game/app/views/cards/_show.html.erb
<div class="col-xs-2">
  <div class="card-wrapper">
    <div class="card">

      <% present card do |card_p| %>
        <%= card_p.display_card %>
      <% end %>

    </div>
  </div>
</div>

concentration_game/app/views/games/_game_over_header.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Congratulations <%= @player.name %>!</h1>
    <h3>You finished in <%= @game.turn %> moves with a score of <%= @player.points %> points.<br/>
      <%= link_to("New game", root_path, class: "btn btn-default-width btn-info") %>
    </h3>
  </div>
</div>

concentration_game/app/views/games/_header.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Turn #<%= @game.turn + 1 %></h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-6">
    <h1><%= @player.name %>, you currently have <%= @player.points %> points.</h1>
  </div>
</div>

concentration_game/app/views/games/_hidden_fields.html.erb
<%= hidden_field_tag :id, @game.id %>
<%= hidden_field_tag :card_one_id, "" %>
<%= hidden_field_tag :card_two_id, "" %>
<%= hidden_field_tag :cards_left, @cards_left.map { |c| c.id } %>

concentration_game/app/views/games/create.js.erb
$("#game-form").fadeOut();
$("#player-form").html("<%= j render "players/new" %>");

concentration_game/app/views/games/new.html.erb
<div class="row">
  <div class="col-xs-5 col-xs-offset-4">
    <h1>Welcome to Concentration!</h1>
  </div>
</div>

<div class="row">

  <%= bootstrap_form_for @game, remote: true do |f| %>
    <%= f.hidden_field :name, value: "Concentration" %>
    <%= f.hidden_field :turn, value: 0 %>


    <div class="col-xs-1 col-xs-offset-4">
      <%= f.submit("Click", remote: true, class: "btn btn-info btn-default-width") %>
    </div>
    <div class="col-xs-6">
      <h3>To start a new game</h3>
    </div>
  <% end %>

</div>

concentration_game/app/views/games/show.html.erb
<div id="game-header">
  <%= render "header" %>
</div>

<div id="points-scored" class="text-red"></div>

<%= form_tag(games_turn_path, method: :post, id: "next-turn", remote: true) do %>

  <div class="row">

    <% @cards_on_board.each do |card| %>

      <div id="card-id-<%= card.id %>">
        <%= render "cards/show", card: card %>
      </div>

    <% end %>

  </div>

  <div id="game-board-hidden-fields">
    <%= render "games/hidden_fields" %>
  </div>

<% end %>

concentration_game/app/views/games/turn.js.erb
<% if @new_cards == nil %>

    $("#points-scored").removeClass("text-green").addClass("text-red").html("-1").fadeIn();
    setTimeout(function() {
        $(".visible").each(function(index, element) {
            $(element).addClass("invisible");
            $(element).removeClass("visible");
        });
        $("#points-scored").fadeOut();
    }, 400);

<% elsif @new_cards.present? %>

    $("#points-scored").removeClass("text-red").addClass("text-green").html("+1").fadeIn();
    setTimeout(function() {
        $("#card-id-" + "<%= @card_one.id %>").html("<%= j render "cards/show", card: @new_cards.first %>");
        $("#card-id-" + "<%= @card_two.id %>").html("<%= j render "cards/show", card: @new_cards.last %>");
        $("#card-id-" + "<%= @card_one.id %>").attr("id", "card-id-" + "<%= @new_cards.first.id %>");
        $("#card-id-" + "<%= @card_two.id %>").attr("id", "card-id-" + "<%= @new_cards.last.id %>");
        $("#points-scored").fadeOut();
    }, 400);

<% else %>

    $("#points-scored").removeClass("text-red").addClass("text-green").html("+1").fadeIn();
    setTimeout(function() {
        $("#card-id-" + "<%= @card_one.id %>").html("<%= j render "cards/blank_card" %>");
        $("#card-id-" + "<%= @card_two.id %>").html("<%= j render "cards/blank_card" %>");
        $("#points-scored").fadeOut();
    }, 400);

<% end %>

$("#game-header").html("<%= j render "header" %>");
$("#game-board-hidden-fields").html("<%= j render "hidden_fields" %>");

if ($('.invisible').length === 0) {

    $("#game-header").html("<%= j render "game_over_header" %>");

}

concentration_game/app/views/games/welcome.html.erb
<div class="row">
  <div class="col-xs-5 col-xs-offset-4">
    <h1>Welcome to Concentration!</h1>
  </div>
</div>

<div id="game-form">
  <div class="row">

    <%= bootstrap_form_for Game.new, remote: true do |f| %>
      <%= f.hidden_field :name, value: "Concentration" %>
      <%= f.hidden_field :turn, value: 0 %>

      <div class="col-xs-6 col-xs-offset-4">
        <h3>
          To start a new game
          <%= f.submit("Click here", remote: true, class: "btn btn-info btn-default-width") %>
        </h3>
      </div>

    <% end %>

  </div>
</div>

<div id="player-form">

</div>

concentration_game/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcentrationGame</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="container-fluid">

    <%= yield %>

  </body>
</html>

concentration_game/app/views/players/_new.html.erb
<%= bootstrap_form_for Player.new do |f| %>

  <%= f.hidden_field :game_id, value: @game.id %>
  <%= f.hidden_field :points, value: 0 %>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-4">
      <div class="col-xs-6">
        <%= f.text_field(:name, label: "Please enter your name.") %>
      </div>
      <div class="col-xs-6 margin-top-25">
        <%= f.submit("Continue") %>
      </div>
    </div>
  </div>

<% end %>